{
 "title": "Server",
 "description": "This dashboard provides cluster admins with the ability to monitor nodes and identify tenant workload bottlenecks. It has been curated from other monitoring dashboards and the helm charts will add PSPs to Prometheus Grafana to make it compatible with all versions of Pivotal Container Services. ",
 "tags": [ "k8s" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server CPU & Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server CPU usage ($interval avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - 100 * (avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])))"
    }
   ]
  },
  {
   "title": "Server memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - sum (node_memory_MemAvailable_bytes{kubernetes_node=~\"^$Node$\"}) / sum (node_memory_MemTotal_bytes{kubernetes_node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode='system'}[1m]))+sum(rate(node_cpu_seconds_total{mode='user'}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))"
    },
    {}
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{kubernetes_node=~\"^$Node$\"}) - sum (node_memory_MemAvailable_bytes{kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (node_memory_MemAvailable_bytes{kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node CPU",
   "type": "table",
   "description": "This Panel will show Node CPU.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))",
     "legendFormat": "{{instance}}  cores "
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "table",
   "description": "This Panel will show Node Memory.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=~\".*\"}",
     "legendFormat": "Server Memory"
    }
   ]
  },
  {
   "title": "Filesystem & Inodes Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Filesystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes - node_filesystem_avail_bytes)/(node_filesystem_size_bytes) * 100 ",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Server filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (node_filesystem_size_bytes - node_filesystem_avail_bytes)/sum(node_filesystem_size_bytes) * 100 "
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) - sum(node_filesystem_avail_bytes)"
    }
   ]
  },
  {
   "title": "Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{device=~\"/dev/.*\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes)"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "description": "This Panel will show Load Average of 1m, 5m and 15m.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{kubernetes_node=~\".*\"}",
     "legendFormat": "Load 1m  {{kubernetes_node}}"
    },
    {
     "expr": "node_load5{kubernetes_node=~\".*\"}",
     "legendFormat": "Load 5m  {{kubernetes_node}}"
    },
    {
     "expr": "node_load15{kubernetes_node=~\".*\"}",
     "legendFormat": "Load 15m  {{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods Network I/O Pressure ($interval avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\"}[$interval]))",
     "legendFormat": "Transmit Bytes"
    }
   ]
  }
 ]
}